[font]
normal = {family = 'FiraCode Nerd Font', style = "Regular"}
bold = {family = 'FiraCode Nerd Font', style = "Bold"}
italic = {family = 'FiraCode Nerd Font', style = "Italic"}
size = 20

[keyboard]
bindings = [
  {action = "ToggleViMode", key = "X", mods = "Control" },
  {action = "ToggleViMode", key = "Escape", mode = "Vi" },
  {action = "ToggleViMode", key = "[", mods = "Control", mode = "Vi" },
]

[general]
# theme
import = [
    "~/.config/alacritty/themes/themes/one_dark.toml"
]

