[font]
normal = {family = 'FiraCode Nerd Font', style = "Regular"}
bold = {family = 'FiraCode Nerd Font', style = "Bold"}
italic = {family = 'FiraCode Nerd Font', style = "Italic"}
size = 20

[keyboard]
bindings = [
  # yakumo
  {chars = "\u0013w", key = "G", mods = "Command" },
  {chars = "\u0018c", key = "C", mods = "Command|Shift" },
  {chars = "\u0018b", key = "B", mods = "Command|Shift" },
]

[general]
# theme
import = [
    "~/.config/alacritty/themes/themes/one_dark.toml"
]

