# Prompt
add_newline = true
scan_timeout = 10

[directory]
truncation_length = 10
truncate_to_repo = false

[battery]
disabled = true

[aws]
format = 'on [$symbol($profile )]($style)'
style = "bold red"
symbol = "AWS:"

[gcloud]
format = 'on [$symbol$account(@$domain)(\($project\))]($style) '
style = "bold blue"
symbol = "GCP:"
